// @generated by api_gen - DO NOT EDIT. Regenerate with cargo regen.

#pragma once

#include <flowi/fl_api.h>
#include <stdbool.h>
#include <stdint.h>
#include <flowi/core/string.h>

#ifdef __cplusplus
extern "C" {
#endif

// Kinds of file system change, reported as a bitmask in FlFileChange::change_types.
typedef enum FlFileChangeType {
    // No change.
    FlFileChangeType_None = 0,
    // File or directory was created.
    FlFileChangeType_Created = 1,
    // File or directory was modified.
    FlFileChangeType_Modified = 2,
    // File or directory was deleted.
    FlFileChangeType_Deleted = 4,
    // File or directory was renamed.
    FlFileChangeType_Renamed = 8,
    // File or directory was moved.
    FlFileChangeType_Moved = 16,
} FlFileChangeType;

typedef struct FlArena FlArena;

// What a watcher should report, passed to FileWatcher::start.
typedef struct FlFileWatcherConfig {
    // Watch subdirectories too.
    bool recursive;
    // Report changes to files.
    bool watch_files;
    // Report changes to directories.
    bool watch_directories;
    // Maximum changes to buffer between polls (0 = platform default).
    uint32_t max_changes;
} FlFileWatcherConfig;

// One file system change event. Paths are borrowed from the batch's arena and stay valid until that
// arena is reset.
typedef struct FlFileChange {
    // Full path to the changed file or directory.
    FlString path;
    // The previous path for a rename or move; empty otherwise.
    FlString old_path;
    // Bitmask of FlFileChangeType values.
    uint32_t change_types;
    // When the change occurred, in microseconds since the epoch.
    uint64_t timestamp;
    // True when the change affects a directory rather than a file.
    bool is_directory;
} FlFileChange;

// A batch of pending changes taken from a watcher: a counted array allocated in the caller's arena.
// Valid until that arena is reset.
typedef struct FlFileChanges {
    // The changes (nullptr when count is 0).
    const FlFileChange* changes;
    // Number of changes in changes.
    uint32_t count;
    // True when the watcher dropped changes because its buffer filled between polls.
    bool has_overflow;
} FlFileChanges;

// Platform-independent file system monitoring for a host that reloads content when it changes on disk.
//
// Start a watcher on a directory, poll has_changes each frame, and take the pending batch into a
// scratch arena when there is something to look at. Taking a batch clears it - each change is reported
// once.
// Direct API - hand-written bodies.
// Start watching path. Returns a watcher handle, or 0 when the path cannot be watched or
// config is null.
FL_API uint32_t fl_file_watcher_start(FlString path, const FlFileWatcherConfig* config);
// Stop watching and release the watcher's resources. No-op on a 0 handle.
FL_API void fl_file_watcher_stop(uint32_t handle);
// True while the watcher is alive and its path still exists.
FL_API bool fl_file_watcher_is_active(uint32_t handle);
// True when changes are pending. Allocates nothing, so it is the cheap per-frame poll.
FL_API bool fl_file_watcher_has_changes(uint32_t handle);
// Take the pending changes into arena and clear them from the watcher.
FL_API FlFileChanges fl_file_watcher_take_changes(uint32_t handle, FlArena* arena);


#ifdef __cplusplus
}
#endif
