// @generated by api_gen - DO NOT EDIT. Regenerate with cargo regen.

#pragma once

#include <flowi/fl_api.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

// Always-on lightweight per-frame profiler that records a hierarchical scope tree
// per thread. Pair frame_begin/frame_end around each frame and begin/end
// around timed scopes; the tree auto-prints when a main-thread frame exceeds its budget.
// Direct API - hand-written bodies.
// Initialize the profiler for the calling (main) thread. Call once at startup.
FL_API void fl_perf_scope_init(void);
// Reset the profiler's thread-local state. Call at application shutdown.
FL_API void fl_perf_scope_destroy(void);
// Open a timing scope named name and return its stack index (pass it to
// end). Returns UINT32_MAX on overflow (the matching end is a no-op).
FL_API uint32_t fl_perf_scope_begin(const char* name);
// Close the timing scope at stack_index (the value begin returned).
FL_API void fl_perf_scope_end(uint32_t stack_index);
// Begin a frame: clear the per-thread scope tree for the new frame.
FL_API void fl_perf_scope_frame_begin(void);
// End a frame: on the main thread, print the scope tree if the frame exceeded
// the budget.
FL_API void fl_perf_scope_frame_end(void);


#ifdef __cplusplus
}
#endif
