// @generated by api_gen - DO NOT EDIT. Regenerate with cargo regen.

#pragma once

#ifdef __cplusplus
extern "C" {
#endif

// General-purpose status code, for subsystems that don't warrant their own status enum
// (arenas, memory, strings, the job system, settings, plugin loading). Success is always 0,
// so if (status) tests for failure. Errors are grouped in ranges of 100 per category, with
// gaps left for growth inside each. Subsystems with many specific failure modes define their
// own enum instead (VfsStatus for file operations, StringParseStatus for parsing).
typedef enum FlStatus {
    // The operation succeeded.
    FlStatus_Success = 0,
    // Generic invalid argument.
    FlStatus_InvalidArgument = 1,
    // A null pointer was passed where a valid pointer is required.
    FlStatus_NullPointer = 2,
    // A value fell outside its valid range.
    FlStatus_OutOfRange = 3,
    // The operation is invalid in the current state.
    FlStatus_InvalidState = 4,
    // An enum value outside the defined set.
    FlStatus_InvalidEnum = 5,
    // Memory allocation failed.
    FlStatus_OutOfMemory = 100,
    // Generic resource exhaustion.
    FlStatus_ResourceExhausted = 101,
    // The operation exceeded a system or configured limit.
    FlStatus_LimitExceeded = 102,
    // The plugin file was not found.
    FlStatus_PluginNotFound = 200,
    // The plugin's shared library failed to load.
    FlStatus_PluginLoadFailed = 201,
    // The plugin is malformed or missing required symbols.
    FlStatus_PluginInvalid = 202,
    // The plugin's API version is incompatible.
    FlStatus_PluginVersionMismatch = 203,
    // The plugin's initialization failed.
    FlStatus_PluginInitFailed = 204,
    // The job queue is at capacity.
    FlStatus_JobQueueFull = 300,
    // The job was canceled before it completed.
    FlStatus_JobCanceled = 301,
    // The job exceeded its timeout.
    FlStatus_JobTimeout = 302,
    // The job's execution failed.
    FlStatus_JobFailed = 303,
    // The setting key was not found.
    FlStatus_SettingNotFound = 400,
    // The setting's value failed to parse.
    FlStatus_SettingParseError = 401,
    // The setting exists but holds a different type.
    FlStatus_SettingTypeMismatch = 402,
    // The setting is read-only.
    FlStatus_SettingReadOnly = 403,
    // The feature is not implemented yet.
    FlStatus_NotImplemented = 900,
    // The operation is not supported.
    FlStatus_Unsupported = 901,
    // Generic or unknown error.
    FlStatus_GenericError = 999,
} FlStatus;


#ifdef __cplusplus
}
#endif
